victordocent/dreams_r_us

app/views/pages/home.html.erb

First pr alban

---

Gemfile.lock
app/models/booking.rb
app/models/dream.rb
app/models/user.rb
app/views/dreams/new.html.erb
config/routes.rb
db/migrate/20231121104836_create_bookings.rb
db/schema.rb
test/models/booking_test.rb

- add booking model
- modify routes
- modify validates on booking & dreams models

Add booking model 2111

---

Gemfile.lock
app/controllers/dreams_controller.rb

added edit, update, and destroy to dreams controller, defined before action find_dream method

edit and destroy methods for dreams

---

app/controllers/dreams_controller.rb

modify the permit so we can access the category

modify the permit so we can access the category

---

app/javascript/controllers/datepicker_controller.js
app/views/layouts/application.html.erb
config/importmap.rb

added datepicker library
created controller

Add flatpickr to project

---

app/controllers/bookings_controller.rb
app/views/bookings/index.html.erb

add lost files + comment from Nicolas

add lost files + comment from Nicolas

---

app/views/bookings/show.html.erb
config/routes.rb

fix routes + view

---

config/routes.rb

add index for booking

---

Gemfile
Gemfile.lock
db/seeds.rb

Added a seed to have some dreams

add seed working

---

app/views/bookings/show.html.erb

*The new code in the show will work only with my previous PR on new merged

added booking dates in a human readable format

---

app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_modal_dream.scss
app/assets/stylesheets/pages/_index.scss
app/assets/stylesheets/pages/_show.scss
app/views/dreams/show.html.erb
app/views/layouts/application.html.erb
app/views/shared/_caroussel.html.erb
app/views/shared/_modal_dream_show.html.erb
config/importmap.rb

Modify dream show 2211

---

app/assets/stylesheets/components/_modal_dream.scss
app/assets/stylesheets/pages/_show.scss
app/assets/stylesheets/pages/_sliding_background.scss

add modif regarding body + show images

add modif regarding body + show images

---

app/controllers/pages_controller.rb
app/views/pages/dashboard.html.erb
app/views/shared/_navbar.html.erb
config/routes.rb

added dashboard + modify links of the navabr

added dashboard + modify links of the navabr

---

app/views/shared/_caroussel.html.erb

change photos

---

app/controllers/bookings_controller.rb
app/views/bookings/edit.html.erb
app/views/bookings/new.html.erb
app/views/bookings/show.html.erb
config/routes.rb

Booking edit and update working
Routes nested and paths changed to make everything work

Booking edit

---

db/seeds.rb

add 5 images to the seed

---

app/views/bookings/new.html.erb
app/views/bookings/show.html.erb
app/views/dreams/show.html.erb

add price tag on the show of the booking

Modify show price 2411

---

app/views/shared/_dashboard_booking_received_table.html.erb
app/views/shared/_dashboard_booking_sent_table.html.erb

fix + add securities not to fail

fix + add securities not to fail

---

app/views/shared/_dashboard_booking_received_table.html.erb
app/views/shared/_dashboard_dream_table.html.erb

Modify table bookings received 2411

Modify table bookings received 2411

---

Gemfile.lock
app/controllers/bookings_controller.rb
app/javascript/controllers/datepicker_controller.js
app/views/bookings/edit.html.erb
app/views/bookings/new.html.erb

done the date picker minimum date to today and error messages implemented for bookings already taken

done the date picker minimum date to today and error messages implemented  for bookings already taken

---

app/controllers/bookings_controller.rb
app/models/booking.rb
app/views/shared/_dashboard_booking_received_table.html.erb
config/routes.rb
db/migrate/20231124111739_add_column_status_in_bookings.rb
db/schema.rb

add booking validation

---

app/models/booking.rb

add status attributes

---

app/views/shared/_dashboard_booking_sent_table.html.erb

add status of the request
